unique_ids:
  assets:
    standard-page.html: 6OUK4YU4WYNTCICYLMFL3CRQ72OORSDK
    theme.css: LHCKTBBZ3JAFC74ZXA3ADVXBYGKX2JS5
  forms:
    Form1: CXL3KXISF63UDRCVSR3T2HFQFZWMTHCC
  modules: {}
  scripts: {}
  server_modules: {}
